import React, { useEffect, useState, useCallback } from 'react';
import toast from 'react-hot-toast';
import { FiSearch, FiEye, FiTrash2, FiPrinter, FiDownload, FiTruck, FiX } from 'react-icons/fi';
import { adAPI } from '../../utils/api';
import { PageHeader, Card, Input, Select, Button, Badge, Table, Tr, Td, EmptyState, Modal } from '../../components/common/UI';

const fmtDate = (d) => d ? new Date(d).toLocaleDateString() : '—';

// Render a row of label/value, skipping empty values.
const DetailRow = ({ label, value }) => {
  if (value === undefined || value === null || value === '' || value === false) return null;
  return (
    <div className="flex justify-between gap-4 py-1.5" style={{ borderBottom: '1px solid var(--border)' }}>
      <span className="text-xs" style={{ color: 'var(--text-muted)' }}>{label}</span>
      <span className="text-xs font-medium text-right" style={{ color: 'var(--text-primary)' }}>{String(value === true ? 'Yes' : value)}</span>
    </div>
  );
};

export default function MyAds() {
  const [ads, setAds] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ q: '', vehicleType: 'all', from: '', to: '' });
  const [viewing, setViewing] = useState(null);
  const [viewLoading, setViewLoading] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const params = {};
      if (filters.q) params.q = filters.q;
      if (filters.vehicleType !== 'all') params.vehicleType = filters.vehicleType;
      if (filters.from) params.from = filters.from;
      if (filters.to) params.to = filters.to;
      const res = await adAPI.getMyAds(params);
      setAds(res.data.ads || []);
    } catch {
      toast.error('Failed to load advertisements.');
    } finally {
      setLoading(false);
    }
  }, [filters]);

  useEffect(() => { load(); }, [load]);

  const openView = async (id) => {
    setViewLoading(true);
    setViewing({ loading: true });
    try {
      const res = await adAPI.getAd(id);
      setViewing(res.data.ad);
    } catch {
      toast.error('Failed to load advertisement.');
      setViewing(null);
    } finally {
      setViewLoading(false);
    }
  };

  const doDelete = async () => {
    const id = confirmDelete._id;
    try {
      await adAPI.deleteAd(id);
      toast.success('Advertisement Deleted Successfully');
      setConfirmDelete(null);
      setAds(a => a.filter(x => x._id !== id));
    } catch {
      toast.error('Failed to delete advertisement.');
    }
  };

  // Build a printable window (also used for PDF via the browser's "Save as PDF").
  const printAd = (ad) => {
    const det = ad.vehicleType === 'new' ? ad.newDetails : ad.usedDetails;
    const rows = det ? Object.entries(det)
      .filter(([k, v]) => !['id', '_id', 'advertisementId', 'createdAt', 'updatedAt'].includes(k) && v !== null && v !== '' && v !== false)
      .map(([k, v]) => `<tr><td style="padding:6px 10px;color:#555;text-transform:capitalize">${k.replace(/([A-Z])/g, ' $1')}</td><td style="padding:6px 10px;font-weight:600">${v === true ? 'Yes' : v}</td></tr>`)
      .join('') : '';
    const html = `<!doctype html><html><head><title>${ad.adId} - ${ad.carTitle}</title>
      <style>body{font-family:Arial,sans-serif;color:#222;padding:32px;max-width:800px;margin:auto}
      h1{color:#2563eb;margin:0 0 4px}h2{font-size:14px;color:#2563eb;border-bottom:2px solid #2563eb;padding-bottom:4px;margin-top:24px}
      table{width:100%;border-collapse:collapse}tr:nth-child(even){background:#f6f8fb}
      .meta{color:#666;font-size:13px;margin-bottom:16px}</style></head><body>
      <h1>Car Hive Advertisement</h1>
      <div class="meta"><b>${ad.adId}</b> · Batch ${ad.batchNumber} · ${ad.vehicleType === 'new' ? 'New Vehicle' : 'Second-Hand Vehicle'} · Posted ${fmtDate(ad.createdAt)}</div>
      <h2>${ad.carTitle}</h2>
      <table>${rows}</table>
      ${det && det.vehicleDescription ? `<h2>Description</h2><p>${det.vehicleDescription}</p>` : ''}
      <p style="margin-top:32px;color:#999;font-size:11px">Generated by Car Hive Freelancer Platform · ${new Date().toLocaleString()}</p>
      </body></html>`;
    const w = window.open('', '_blank');
    if (!w) { toast.error('Allow pop-ups to export.'); return; }
    w.document.write(html);
    w.document.close();
    w.focus();
    setTimeout(() => w.print(), 350);
  };

  const det = viewing && !viewing.loading ? (viewing.vehicleType === 'new' ? viewing.newDetails : viewing.usedDetails) : null;

  return (
    <div>
      <PageHeader title="My Ads" subtitle="Manage your vehicle advertisements" />

      <div className="p-4 sm:p-6 space-y-4">
        {/* Search & filters */}
        <Card>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 items-end">
            <div className="relative">
              <label className="block text-xs font-medium mb-1.5" style={{ color: 'var(--text-secondary)' }}>Search (Ad ID / Batch / Title)</label>
              <FiSearch className="absolute left-3 bottom-3" size={14} style={{ color: 'var(--text-muted)' }} />
              <input className="input-field pl-9" placeholder="Search…" value={filters.q}
                onChange={e => setFilters(f => ({ ...f, q: e.target.value }))} />
            </div>
            <Select label="Vehicle Type" value={filters.vehicleType} onChange={e => setFilters(f => ({ ...f, vehicleType: e.target.value }))}>
              <option value="all">All</option>
              <option value="new">New Vehicle</option>
              <option value="used">Second-Hand</option>
            </Select>
            <Input label="From Date" type="date" value={filters.from} onChange={e => setFilters(f => ({ ...f, from: e.target.value }))} />
            <Input label="To Date" type="date" value={filters.to} onChange={e => setFilters(f => ({ ...f, to: e.target.value }))} />
          </div>
        </Card>

        {/* Table */}
        <Card padding={false}>
          {(!loading && ads.length === 0) ? (
            <EmptyState icon={<FiTruck />} title="No advertisements found" description="Try adjusting filters or post your first ad." />
          ) : (
            <Table headers={['Ad ID', 'Batch Number', 'Car Title', 'Type', 'Date Posted', 'Status', 'Actions']} loading={loading}>
              {ads.map(ad => (
                <Tr key={ad._id}>
                  <Td bold>{ad.adId}</Td>
                  <Td>{ad.batchNumber}</Td>
                  <Td>{ad.carTitle}</Td>
                  <Td>{ad.vehicleType === 'new' ? 'New' : 'Used'}</Td>
                  <Td>{fmtDate(ad.createdAt)}</Td>
                  <Td><Badge status="active">{ad.status}</Badge></Td>
                  <Td>
                    <div className="flex items-center gap-2">
                      <button onClick={() => openView(ad._id)} title="View" className="p-1.5 rounded-lg" style={{ color: 'var(--neon)', background: 'rgba(59,130,246,0.1)' }}><FiEye size={14}/></button>
                      <button onClick={() => setConfirmDelete(ad)} title="Delete" className="p-1.5 rounded-lg" style={{ color: 'var(--red)', background: 'rgba(239,68,68,0.1)' }}><FiTrash2 size={14}/></button>
                    </div>
                  </Td>
                </Tr>
              ))}
            </Table>
          )}
        </Card>
      </div>

      {/* View modal */}
      <Modal isOpen={!!viewing} onClose={() => setViewing(null)} title="Advertisement Details" maxWidth="640px">
        {viewLoading || viewing?.loading ? (
          <div className="py-10 text-center text-sm" style={{ color: 'var(--text-muted)' }}>Loading…</div>
        ) : viewing && (
          <div>
            <div className="flex items-start justify-between mb-3">
              <div>
                <div className="font-display font-bold text-lg" style={{ color: 'var(--text-primary)' }}>{viewing.carTitle}</div>
                <div className="text-xs" style={{ color: 'var(--text-muted)' }}>{viewing.adId} · Batch {viewing.batchNumber} · {viewing.vehicleType === 'new' ? 'New Vehicle' : 'Second-Hand Vehicle'}</div>
              </div>
              <Badge status="active">{viewing.status}</Badge>
            </div>

            <div className="max-h-[55vh] overflow-y-auto pr-1">
              {det && Object.entries(det)
                .filter(([k]) => !['id', '_id', 'advertisementId', 'createdAt', 'updatedAt', 'vehicleDescription'].includes(k))
                .map(([k, v]) => <DetailRow key={k} label={k.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase())} value={v} />)}
              {det?.vehicleDescription && (
                <div className="mt-3">
                  <div className="text-xs font-semibold mb-1" style={{ color: 'var(--text-muted)' }}>Description</div>
                  <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>{det.vehicleDescription}</p>
                </div>
              )}
            </div>

            <div className="flex items-center gap-2 mt-5">
              <Button onClick={() => printAd(viewing)} variant="ghost"><FiDownload size={14}/> PDF Download</Button>
              <Button onClick={() => printAd(viewing)} variant="ghost"><FiPrinter size={14}/> Print</Button>
            </div>
          </div>
        )}
      </Modal>

      {/* Delete confirmation */}
      <Modal isOpen={!!confirmDelete} onClose={() => setConfirmDelete(null)} title="Delete Advertisement" maxWidth="400px">
        <p className="text-sm mb-5" style={{ color: 'var(--text-secondary)' }}>
          Are you sure you want to delete this advertisement?
        </p>
        <div className="flex items-center gap-2 justify-end">
          <Button variant="ghost" onClick={() => setConfirmDelete(null)}>No</Button>
          <Button variant="danger" onClick={doDelete}><FiTrash2 size={14}/> Yes</Button>
        </div>
      </Modal>
    </div>
  );
}
